# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-11 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='idName',
            field=models.CharField(default='stuff', max_length=250),
        ),
    ]
