# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-22 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='member_type',
            field=models.CharField(choices=[('1', 'Student'), ('2', 'Teacher'), ('3', 'Administrator'), ('4', 'Location')], max_length=50),
        ),
    ]
