# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-11 02:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0002_teacher_idname'),
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='defaultOrgin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='srt_teacher', to='Teacher.Teacher'),
        ),
    ]
