# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-04 13:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Teacher', '0001_initial'),
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('startTimeRequested', models.DateTimeField()),
                ('endTimeRequested', models.DateTimeField()),
                ('timeLeftOrigin', models.DateTimeField(null=True)),
                ('timeArrivedDestination', models.DateTimeField(null=True)),
                ('type', models.CharField(choices=[(1, 'Teacher Pass'), (2, 'Other Pass')], max_length=48)),
                ('location', models.CharField(max_length=12, null=True)),
                ('description', models.CharField(max_length=960, null=True)),
                ('destinationTeacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destinationTeacher', to='Teacher.Teacher')),
                ('originTeacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pass_origin_teacher', to='Teacher.Teacher')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pass_student', to='Student.Student')),
            ],
        ),
    ]
