# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-05 01:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Passes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pass',
            name='destinationTeacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destinationTeacher', to='Teacher.Teacher'),
        ),
        migrations.AlterField(
            model_name='pass',
            name='type',
            field=models.CharField(choices=[('1', 'Teacher Pass'), ('2', 'Other Pass')], max_length=48),
        ),
    ]
