# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-20 23:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0002_teacher_idname'),
        ('Passes', '0003_auto_20180705_0148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pass',
            name='location',
        ),
        migrations.RemoveField(
            model_name='pass',
            name='destinationTeacher',
        ),
        migrations.RemoveField(
            model_name='pass',
            name='type',
        ),
        migrations.AddField(
            model_name='pass',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pass',
            name='endTimeRequested',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pass',
            name='startTimeRequested',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pass',
            name='timeArrivedDestination',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pass',
            name='timeLeftOrigin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='LocationPass',
            fields=[
                ('pass_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='Passes.Pass')),
                ('location', models.CharField(blank=True, max_length=12, null=True)),
            ],
            bases=('Passes.pass',),
        ),
        migrations.CreateModel(
            name='SRTPass',
            fields=[
                ('pass_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='Passes.Pass')),
                ('session', models.CharField(blank=True, max_length=1, null=True)),
                ('timeLeftDestination', models.TimeField(blank=True, null=True)),
                ('timeArrivedOrigin', models.TimeField(blank=True, null=True)),
            ],
            bases=('Passes.pass',),
        ),
        migrations.CreateModel(
            name='TeacherPass',
            fields=[
                ('pass_ptr',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True,
                                      serialize=False, to='Passes.Pass')),
                ('destinationTeacher',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                   related_name='destinationTeacher', to='Teacher.Teacher')),
            ],
            bases=('Passes.pass',),
        ),
    ]
