# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-21 01:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0002_teacher_idname'),
        ('Passes', '0004_auto_20180820_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='srtpass',
            name='destinationTeacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destinationTeacherSRT', to='Teacher.Teacher'),
        ),
    ]
