# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-25 17:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Passes', '0005_srtpass_destinationteacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherpass',
            name='pass_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Passes.Pass'),
        ),
    ]
