# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-09-02 17:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='idName',
            new_name='name',
        ),
    ]
