# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-01-22 00:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_auto_20180921_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='pass',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pass_creator', to='server.Teacher'),
        ),
    ]
