# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-02-03 03:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_pass_requester'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='defaultOrgin',
            new_name='defaultOrigin',
        ),
    ]
